### ISSUE TITLE
Unicode - funny characters?

### ISSUE THREAD

**Issue by dgmckenna** [pettarin/export-kobo#2]
Hello, thank you so much for making this tool. It's invaluable.

I used Python 2.7 and got many question marks.
I tried Python 3 as suggested and got some funny characters, below are the list of characters and underneath them what I search/replaced in my document to fix. One of the double quotes is a smart double quote, (opening/closing) but I'm just using "

Is there a way to address this with the existing code / configuration?
Thank you again for a great utility!

â€™
'

â€”
,

â€œ
"

â€
"

**Comment by pettarin** [comment]
Hi,

you are welcome. I have a couple of questions to triage your issue:

1. What OS are you using? Windows? MacOS? Linux?

2. Did you try outputting to file (--output yourfile.txt), instead of 
standard output? Especially on Windows, the encoding of your 
shell/command prompt matters --- and Windows defaults to a not-UTF-8 
encoding. The shell encoding becomes irrelevant if you output to file. 
Alternatively, you might try changing the shell encoding to UTF-8.

3. If none of the above works, I would need your input KoboReader.sqlite 
file and output .txt file (and maybe a screenshot showing the problem) 
to investigate. You can send those to me privately, you can find my 
email address here: http://www.albertopettarin.it/contact.html

HTH,

AP

**Comment by dgmckenna** [comment]
The --output yourfile.txt seems to work perfectly.

The CSV export has the issues. I'll close this since there is a workaround. Sorry for the delay in updating this.

**Comment by pettarin** [comment]
Thank you for letting me know. Yes, outputting Unicode to Windows 
terminals is tricky because: Python 2 does not have good support (Python 
3 is better w.r.t. this) and, more importantly, Windows have esoteric 
default encodings (codepages as they call them).

The --output option works because it directly writes the "correct" bytes 
to file, the terminal does not come into play, that's why I recommend 
using it.
